# Generated by Django 4.0.5 on 2022-06-29 17:47

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(upload_to=users.models.get_upload_path),
        ),
    ]
