version: "3.8"

services:
  database:
    image: postgres:14-alpine
    restart: always
    ports:
      - "5432:5432"
    env_file:
      .env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  django:
    build:
      dockerfile: django_app/Dockerfile
    volumes:
      - ./django_app/staticfiles:/var/www/static/
      - ./django_app/media:/var/www/media/
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --no-input &&
             gunicorn --bind 0.0.0.0:8000 django_app.wsgi"
    environment:
      IN_DOCKER: 1
    ports:
      - "8000:8000"
    depends_on:
      - database
      - flask
  flask:
    build:
      dockerfile: flask_cv/Dockerfile
    ports:
      - "5001:5001"
    command: >
      sh -c "python app.py"
    environment:
      FLASK_APP: app
  nginx:
    build:
      dockerfile: nginx/Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./django_app/staticfiles:/var/www/static
      - ./django_app/media:/var/www/media
    depends_on:
      - django
      - flask
#  volumes:
#    static_volume:
#    media_volume:

